language: go
env:
- GO111MODULE=on
go:
- 1.11.x
install: true
before_script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s -- -b $(go env GOPATH)/bin v1.15.0
- go get github.com/mattn/goveralls
- go mod download
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- echo $TRAVIS_TAG
script:
- golangci-lint run
- go build -o proxy .
- go test -v -race ./...
- "$GOPATH/bin/goveralls -service=travis-ci"
deploy:
  provider: releases
  api_key:
    secure: EGsQeDz6vC/tB2ioyWAURsrbFtd2K0utbhWH2pl8gr6Rwy7D2qBz38QUq57iYP+1WI7QEeAn4L6HFug29fGNI4Q7sw2760qG69mqfNONJJRnvPYMKMx9hWHxGqo79bc5vaNieHFOlz3yN8rj3x3x45tRaGMHpC9HIFPxNIljl4CqAqX7DoEGW64xICwn846XgF1DFXcna9fnoAzr+yJMtujWxtCMmN/Oqs5J4p/g7N6Ld/sEOuR3gnXWOsbrAfUlYCyjzUq/yWCyIiSUNSrnCjVYUGa7G9i/U5rudVQm5uXYvVL00+GXZPJGpk4ZVCJFbebY6wz+YfJOB9iNYzK8nTzwUsHj/dlU4LNZoSyL3wm/HyCB8Ta3m9dgT7egqTpBolt4hPu0Wyzzota6c+g9JXcaDMPIldqEVMVxWpxjpf0jVwqLZcOlVqSta6Rspa8Cna/6XmMxe9yKgqoYpUb2AXDmHWbF6yUEZC1yt7biKg6qnaqgJSiMwpG9gXVEFRQeFVF563RBFcFKFNd446hAS/Uq8x4KAgimUAU2Ho6IyI6fZEEVXj6H2BlcFgpxH/tHMXVh66eL9uyIO/ws5RXNxvFT2v8H2Hof8Qo0qxM/ukJ+GOncRp0fnU9UMpKLhYbKGcHliVNBk6nanQq0OGczGwgAdqsp7isxhmZ/ugWhMKM=
  file: proxy
  skip_cleanup: true
  on:
    repo: xUnholy/go-proxy
    branch: feature/#14
    tags: true
